Future text probe syntax support
Added support for a future breaking change in text probe syntax.
Main change: expected values must be wrapped in string quotes.
Exception: true, false, empty string and numbers do not need
string quotes.

The new syntax is currently disabled by default.
It can be enabled by setting:
  -Dcpr.permitImplicitStringConversion=false

Also improved the handling of multiline strings. String literals in text
probes can now use some basic escape sequences (\n, \" and \\).

If "future" syntax is enabled, the  "actual" result of a text probe for
multiline strings is no longer presented as an array of strings.
For example, if the result is "A\nB", it would previously be encoded
as "[A, B]". With the future syntax, the string is kept as-is.